server:
  port: 8888
  servlet:
    context-path: /provider8001

mybatis:
  typeAliasesPackage: com.lp.springcloud.entity
  config-location: classpath:mybatis-config.xml
  mapper-locations: classpath:mapper/*.xml

spring:
  datasource:
    url: jdbc:mysql://192.168.1.110:3306/forum518?characterEncoding=utf8&useSSL=true
    username: root
    password: admin
    driver-class-name: com.mysql.jdbc.Driver
  thymeleaf:
    prefix: classpath:/templates/
    #HTML5
    mode: LEGACYHTML5
    encoding: UTF-8
    cache: false
    servlet:
      content-type: text/html