server:
  port: 80
  context-path: /consumer80
eureka:
  client:
    register-with-eureka: false #是否想注册中心注册自己
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka/,http://eureka7002.com:7002/eureka/,http://eureka7003.com:7003/eureka/
#
  #hystrix:
  #  command:
  #    default:
  #      execution:
  #        isolation:
  #          thread:
  #            timeoutInMilliseconds: 5000
  feign:
    hystrix:
      enabled: true